//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApiBuilder.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopApiBuilder.App.Resources.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add entity.
        /// </summary>
        internal static string AddEntityBtn {
            get {
                return ResourceManager.GetString("AddEntityBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add entity class.
        /// </summary>
        internal static string AddEntityClassBtn {
            get {
                return ResourceManager.GetString("AddEntityClassBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add property.
        /// </summary>
        internal static string AddPropertyBtn {
            get {
                return ResourceManager.GetString("AddPropertyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply migration automatically.
        /// </summary>
        internal static string ApplyMigrationLabel {
            get {
                return ResourceManager.GetString("ApplyMigrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        internal static string ArchitectureType_Clean {
            get {
                return ResourceManager.GetString("ArchitectureType.Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string ArchitectureType_Custom {
            get {
                return ResourceManager.GetString("ArchitectureType.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-layered.
        /// </summary>
        internal static string ArchitectureType_ThreeLayered {
            get {
                return ResourceManager.GetString("ArchitectureType.ThreeLayered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture type.
        /// </summary>
        internal static string ArchitectureTypeLabel {
            get {
                return ResourceManager.GetString("ArchitectureTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to infrastructure setup.
        /// </summary>
        internal static string BackToInfraBtn {
            get {
                return ResourceManager.GetString("BackToInfraBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Folder.
        /// </summary>
        internal static string ChooseFolderBtn {
            get {
                return ResourceManager.GetString("ChooseFolderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes for solution &quot;{0}&quot; were succesfully created!.
        /// </summary>
        internal static string ClassesCreatedMessage {
            get {
                return ResourceManager.GetString("ClassesCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseBtn {
            get {
                return ResourceManager.GetString("CloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file &quot;{0}&quot; was succesfully created in &quot;{1}&quot;..
        /// </summary>
        internal static string ConfigFileCreatedMessage {
            get {
                return ResourceManager.GetString("ConfigFileCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config File Name.
        /// </summary>
        internal static string ConfigFileNameLabel {
            get {
                return ResourceManager.GetString("ConfigFileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file &quot;{0}&quot; was succesfully created in &quot;{1}&quot;..
        /// </summary>
        internal static string ConfigFileText {
            get {
                return ResourceManager.GetString("ConfigFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ConfigFileTitleText {
            get {
                return ResourceManager.GetString("ConfigFileTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation dialog.
        /// </summary>
        internal static string ConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is required.
        /// </summary>
        internal static string ConnectionStringIsRequiredError {
            get {
                return ResourceManager.GetString("ConnectionStringIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string.
        /// </summary>
        internal static string ConnectionStringLabel {
            get {
                return ResourceManager.GetString("ConnectionStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create classes.
        /// </summary>
        internal static string CreateClassesBtn {
            get {
                return ResourceManager.GetString("CreateClassesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create projects.
        /// </summary>
        internal static string CreateProjectsBtn {
            get {
                return ResourceManager.GetString("CreateProjectsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Solution.
        /// </summary>
        internal static string CreateSolutionBtn {
            get {
                return ResourceManager.GetString("CreateSolutionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use C# keywords.
        /// </summary>
        internal static string CsharpErrorAttribute {
            get {
                return ResourceManager.GetString("CsharpErrorAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom architecture setup.
        /// </summary>
        internal static string CustomArchitectureSetupLink {
            get {
                return ResourceManager.GetString("CustomArchitectureSetupLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Architecture Setup.
        /// </summary>
        internal static string CustomArchitectureSetupPageTitle {
            get {
                return ResourceManager.GetString("CustomArchitectureSetupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name (default value: {0}Db).
        /// </summary>
        internal static string DatabaseNameLabel {
            get {
                return ResourceManager.GetString("DatabaseNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} directory name.
        /// </summary>
        internal static string DirectoryPathLabel {
            get {
                return ResourceManager.GetString("DirectoryPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Definition.
        /// </summary>
        internal static string DomainDefinitionPageTitle {
            get {
                return ResourceManager.GetString("DomainDefinitionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the &quot;{0}&quot; entity?.
        /// </summary>
        internal static string DoYouWantToRemoveEntityMessage {
            get {
                return ResourceManager.GetString("DoYouWantToRemoveEntityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entity.
        /// </summary>
        internal static string EditEntityBtn {
            get {
                return ResourceManager.GetString("EditEntityBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity with name &quot;{0}&quot; is already exists..
        /// </summary>
        internal static string EntityError {
            get {
                return ResourceManager.GetString("EntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity name.
        /// </summary>
        internal static string EntityNameTableLable {
            get {
                return ResourceManager.GetString("EntityNameTableLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity plural name.
        /// </summary>
        internal static string EntityPluralNameLabel {
            get {
                return ResourceManager.GetString("EntityPluralNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution timeout: something went wrong!.
        /// </summary>
        internal static string ExecutionTimeoutErrorMessage {
            get {
                return ResourceManager.GetString("ExecutionTimeoutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        internal static string FieldIsRequiredErrorAttribute {
            get {
                return ResourceManager.GetString("FieldIsRequiredErrorAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your solution is ready to use.
        /// </summary>
        internal static string FinalPageMessage {
            get {
                return ResourceManager.GetString("FinalPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string HostLabel {
            get {
                return ResourceManager.GetString("HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        internal static string IdTypeLabel {
            get {
                return ResourceManager.GetString("IdTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure settings.
        /// </summary>
        internal static string InfrastructureSettingsPageTitle {
            get {
                return ResourceManager.GetString("InfrastructureSettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextBtn {
            get {
                return ResourceManager.GetString("NextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkBtn {
            get {
                return ResourceManager.GetString("OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} project name.
        /// </summary>
        internal static string OldProjectNameLabel {
            get {
                return ResourceManager.GetString("OldProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (optional).
        /// </summary>
        internal static string PasswordOptionalLabel {
            get {
                return ResourceManager.GetString("PasswordOptionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Portlabel {
            get {
                return ResourceManager.GetString("Portlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects for solution &quot;{0}&quot; were succesfully created!.
        /// </summary>
        internal static string ProjectsCreatedMessage {
            get {
                return ResourceManager.GetString("ProjectsCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name is required.
        /// </summary>
        internal static string PropertyNameRequiredError {
            get {
                return ResourceManager.GetString("PropertyNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name.
        /// </summary>
        internal static string PropertyNameTableLable {
            get {
                return ResourceManager.GetString("PropertyNameTableLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type is required.
        /// </summary>
        internal static string PropertyTypeRequiredError {
            get {
                return ResourceManager.GetString("PropertyTypeRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type.
        /// </summary>
        internal static string PropertyTypeTableLable {
            get {
                return ResourceManager.GetString("PropertyTypeTableLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ResultDialogSuccessTitle {
            get {
                return ResourceManager.GetString("ResultDialogSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string SetupBtn {
            get {
                return ResourceManager.GetString("SetupBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup DB connection + Add initial migration.
        /// </summary>
        internal static string SetupDbBtn {
            get {
                return ResourceManager.GetString("SetupDbBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution name is required.
        /// </summary>
        internal static string SolurionNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("SolurionNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution &quot;{0}&quot; was successfully created!.
        /// </summary>
        internal static string SolutionCreatedMessage {
            get {
                return ResourceManager.GetString("SolutionCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution setup.
        /// </summary>
        internal static string SolutionCreationPageTitle {
            get {
                return ResourceManager.GetString("SolutionCreationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Name.
        /// </summary>
        internal static string SolutionNameLabel {
            get {
                return ResourceManager.GetString("SolutionNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Path.
        /// </summary>
        internal static string SolutionPathInputLabel {
            get {
                return ResourceManager.GetString("SolutionPathInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution path is required.
        /// </summary>
        internal static string SolutionPathRequiredErrorMessage {
            get {
                return ResourceManager.GetString("SolutionPathRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use special symbols.
        /// </summary>
        internal static string SpecialSymbolsErrorAttribute {
            get {
                return ResourceManager.GetString("SpecialSymbolsErrorAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Provider.
        /// </summary>
        internal static string SQLProviderMessage {
            get {
                return ResourceManager.GetString("SQLProviderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL Server.
        /// </summary>
        internal static string SqlProviders_MSSqlServer {
            get {
                return ResourceManager.GetString("SqlProviders.MSSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string SqlProviders_Other {
            get {
                return ResourceManager.GetString("SqlProviders.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postgres.
        /// </summary>
        internal static string SqlProviders_Postgres {
            get {
                return ResourceManager.GetString("SqlProviders.Postgres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server name.
        /// </summary>
        internal static string SQLServerNameLabel {
            get {
                return ResourceManager.GetString("SQLServerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL setup.
        /// </summary>
        internal static string SqlSetupPageTitle {
            get {
                return ResourceManager.GetString("SqlSetupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested connection string.
        /// </summary>
        internal static string SuggestedConnectionStringLabel {
            get {
                return ResourceManager.GetString("SuggestedConnectionStringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *If you want to add the navigation property, you won&apos;t need to create TypeId property manually.
        /// </summary>
        internal static string TypeIdTipLable {
            get {
                return ResourceManager.GetString("TypeIdTipLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Config File.
        /// </summary>
        internal static string UploadConfigFileBtn {
            get {
                return ResourceManager.GetString("UploadConfigFileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (optional).
        /// </summary>
        internal static string UsernameOptionalLabel {
            get {
                return ResourceManager.GetString("UsernameOptionalLabel", resourceCulture);
            }
        }
    }
}
